=== olen4ixxx/TaskXmlBank/src/test/resources/depositTest.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="accounts"
        xmlns:tns="accounts"
        elementFormDefault="qualified">
    <element name="accounts">
        <complexType>
            <sequence>
                <element ref="tns:account" minOccurs="2" maxOccurs="100"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="account">
        <sequence>
            <element name="bank-name" type="string"/>
            <element name="depositor-name" type="tns:depositor-name"/>
            <element name="currency" type="tns:currency"/>
            <element name="registration-date" type="date"/>
            <element name="amount" type="tns:amount"/>
        </sequence>
        <attribute name="id" type="tns:account-id" use="required"/>
        <attribute name="occupation" use="optional" default="IT"/>
    </complexType>

    <simpleType name="depositor-name">
        <restriction base="string">
            <pattern value="[A-Z]([a-z])+[\s][A-Z]([a-z])+"/>
        </restriction>
    </simpleType>
    <simpleType name="currency">
        <restriction base="string">
            <enumeration value="USD"/>
            <enumeration value="EUR"/>
            <enumeration value="BYN"/>
            <enumeration value="RUB"/>
        </restriction>
    </simpleType>
    <simpleType name="amount">
        <restriction base="decimal">
            <fractionDigits value="2"/>
        </restriction>
    </simpleType>
    <simpleType name="account-id">
        <restriction base="ID">
            <pattern value="[A-Z]{2}[0-9]{2}"/>
        </restriction>
    </simpleType>

    <complexType name="checking-account">
        <complexContent>
            <extension base="tns:account">
                <sequence>
                    <element name="payment-system" type="tns:payment-system"/>
                    <element name="cashback" type="tns:cashback"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <simpleType name="payment-system">
        <restriction base="string">
            <enumeration value="Visa"/>
            <enumeration value="MasterCard"/>
            <enumeration value="UnionPay"/>
        </restriction>
    </simpleType>
    <simpleType name="cashback">
        <restriction base="nonNegativeInteger">
            <minInclusive value="0"/>
            <maxInclusive value="5"/>
        </restriction>
    </simpleType>

    <complexType name="deposit">
        <complexContent>
            <extension base="tns:account">
                <sequence>
                    <element name="profitability" type="tns:profitability"/>
                    <element name="deposit-term" type="positiveInteger"/>
                    <element name="callable" type="boolean"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <simpleType name="profitability">
        <restriction base="nonNegativeInteger">
            <minInclusive value="5"/>
            <maxInclusive value="20"/>
        </restriction>
    </simpleType>

    <element name="account" type="tns:account" abstract="true"/>
    <element name="checking-account" type="tns:checking-account" substitutionGroup="tns:account"/>
    <element name="deposit" type="tns:deposit" substitutionGroup="tns:account"/>
</schema>

=== olen4ixxx/TaskXmlBank/src/test/resources/depositTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<accounts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="accounts"
          xsi:noNamespaceSchemaLocation="depositTest.xsd">
    <checking-account occupation="Medicine" id="BY01">
        <bank-name>ALFA</bank-name>
        <depositor-name>Le Na</depositor-name>
        <currency>USD</currency>
        <registration-date>2011-11-11</registration-date>
        <amount>100.11</amount>
        <payment-system>Visa</payment-system>
        <cashback>2</cashback>
    </checking-account>
    <deposit id="BY02">
        <bank-name>ALFA</bank-name>
        <depositor-name>Le Nas</depositor-name>
        <currency>USD</currency>
        <registration-date>2011-11-11</registration-date>
        <amount>100.12</amount>
        <profitability>5</profitability>
        <deposit-term>12</deposit-term>
        <callable>false</callable>
    </deposit>
    <checking-account occupation="Medicine" id="BY03">
        <bank-name>ALFA</bank-name>
        <depositor-name>Le Nasa</depositor-name>
        <currency>USD</currency>
        <registration-date>2011-11-11</registration-date>
        <amount>100.13</amount>
        <payment-system>Visa</payment-system>
        <cashback>0</cashback>
    </checking-account>
    <deposit id="BY04">
        <bank-name>ALFA</bank-name>
        <depositor-name>Le Nasan</depositor-name>
        <currency>USD</currency>
        <registration-date>2011-11-11</registration-date>
        <amount>100.14</amount>
        <profitability>5</profitability>
        <deposit-term>12</deposit-term>
        <callable>false</callable>
    </deposit>
    <checking-account id="BY05" occupation="Medicine">
        <bank-name>ALFA</bank-name>
        <depositor-name>Le Nasano</depositor-name>
        <currency>USD</currency>
        <registration-date>2011-11-11</registration-date>
        <amount>100.15</amount>
        <payment-system>Visa</payment-system>
        <cashback>2</cashback>
    </checking-account>
    <deposit id="BY06">
        <bank-name>ALFA</bank-name>
        <depositor-name>Le Nasanov</depositor-name>
        <currency>USD</currency>
        <registration-date>2011-11-11</registration-date>
        <amount>100.16</amount>
        <profitability>5</profitability>
        <deposit-term>12</deposit-term>
        <callable>false</callable>
    </deposit>
    <checking-account id="BY07" occupation="Medicine">
        <bank-name>ALFA</bank-name>
        <depositor-name>Le Nasanovi</depositor-name>
        <currency>USD</currency>
        <registration-date>2011-11-11</registration-date>
        <amount>100.17</amount>
        <payment-system>Visa</payment-system>
        <cashback>2</cashback>
    </checking-account>
    <deposit id="BY08">
        <bank-name>ALFA</bank-name>
        <depositor-name>Le Nasanovic</depositor-name>
        <currency>USD</currency>
        <registration-date>2011-11-11</registration-date>
        <amount>100.18</amount>
        <profitability>5</profitability>
        <deposit-term>12</deposit-term>
        <callable>false</callable>
    </deposit>
    <checking-account id="BY09" occupation="Medicine">
        <bank-name>ALFA</bank-name>
        <depositor-name>Le Nasanovich</depositor-name>
        <currency>USD</currency>
        <registration-date>2011-11-11</registration-date>
        <amount>100.19</amount>
        <payment-system>Visa</payment-system>
        <cashback>2</cashback>
    </checking-account>
    <deposit id="BY10">
        <bank-name>ALFA</bank-name>
        <depositor-name>Leo Na</depositor-name>
        <currency>USD</currency>
        <registration-date>2011-11-11</registration-date>
        <amount>100.20</amount>
        <profitability>5</profitability>
        <deposit-term>12</deposit-term>
        <callable>false</callable>
    </deposit>
    <checking-account id="BY11" occupation="Medicine">
        <bank-name>ALFA</bank-name>
        <depositor-name>Leon Nas</depositor-name>
        <currency>USD</currency>
        <registration-date>2011-11-11</registration-date>
        <amount>100.21</amount>
        <payment-system>UnionPay</payment-system>
        <cashback>2</cashback>
    </checking-account>
    <deposit id="BY12">
        <bank-name>ALFA</bank-name>
        <depositor-name>Leoni Nas</depositor-name>
        <currency>USD</currency>
        <registration-date>2011-11-11</registration-date>
        <amount>100.22</amount>
        <profitability>5</profitability>
        <deposit-term>12</deposit-term>
        <callable>false</callable>
    </deposit>
    <checking-account id="BY13" occupation="Medicine">
        <bank-name>ALFA</bank-name>
        <depositor-name>Leonid Nas</depositor-name>
        <currency>USD</currency>
        <registration-date>2011-11-11</registration-date>
        <amount>100.23</amount>
        <payment-system>MasterCard</payment-system>
        <cashback>2</cashback>
    </checking-account>
    <deposit id="BY14">
        <bank-name>ALFA</bank-name>
        <depositor-name>Leo Nasa</depositor-name>
        <currency>RUB</currency>
        <registration-date>2011-11-11</registration-date>
        <amount>100.24</amount>
        <profitability>5</profitability>
        <deposit-term>12</deposit-term>
        <callable>false</callable>
    </deposit>
    <checking-account id="BY15" occupation="Medicine">
        <bank-name>ALFA</bank-name>
        <depositor-name>Leon Nasan</depositor-name>
        <currency>BYN</currency>
        <registration-date>2011-11-11</registration-date>
        <amount>100.25</amount>
        <payment-system>Visa</payment-system>
        <cashback>2</cashback>
    </checking-account>
    <deposit id="BY16" occupation="Finance">
        <bank-name>BGPB</bank-name>
        <depositor-name>Leonid Nasanovich</depositor-name>
        <currency>USD</currency>
        <registration-date>2007-07-07</registration-date>
        <amount>10000.26</amount>
        <profitability>20</profitability>
        <deposit-term>120</deposit-term>
        <callable>true</callable>
    </deposit>
</accounts>
